-- -- ================================================================
-- -- V7__more_seed_data.sql
-- --
-- -- REPURPOSED: Initial seed data for the 3-tier product hierarchy.
-- -- (ProductBase → ListingVariant → Sku)
-- --
-- -- This script adds 30 products, each with 3 color variants
-- -- and 4 sizes per variant (360 SKUs total).
-- -- ================================================================

-- -- 1. CLEANUP (Optional but helpful for development freshness)
-- TRUNCATE TABLE listing_variant_images CASCADE;
-- TRUNCATE TABLE skus CASCADE;
-- TRUNCATE TABLE listing_variants CASCADE;
-- TRUNCATE TABLE product_bases CASCADE;

-- -- 2. SCHEMA PRE-REQUISITES (Ensures V7 can run even before V12 is reached)
-- CREATE TABLE IF NOT EXISTS product_bases (
--     id                  BIGSERIAL       PRIMARY KEY,
--     erp_template_code   VARCHAR(64)     NOT NULL UNIQUE,
--     name                VARCHAR(255),
--     created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
--     updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
--     version             BIGINT          NOT NULL DEFAULT 0
-- );

-- CREATE TABLE IF NOT EXISTS listing_variants (
--     id                  BIGSERIAL       PRIMARY KEY,
--     product_base_id     BIGINT          NOT NULL REFERENCES product_bases(id),
--     color_key           VARCHAR(64)     NOT NULL,
--     slug                VARCHAR(255)    NOT NULL UNIQUE,
--     web_description     TEXT,
--     last_sync_at        TIMESTAMPTZ,
--     top_selling         BOOLEAN         NOT NULL DEFAULT FALSE,
--     created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
--     updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
--     version             BIGINT          NOT NULL DEFAULT 0,
--     UNIQUE (product_base_id, color_key)
-- );

-- CREATE TABLE IF NOT EXISTS listing_variant_images (
--     id                    BIGSERIAL     PRIMARY KEY,
--     listing_variant_id    BIGINT        NOT NULL REFERENCES listing_variants(id) ON DELETE CASCADE,
--     image_url             TEXT          NOT NULL,
--     sort_order            INTEGER       NOT NULL DEFAULT 0,
--     created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
-- );

-- CREATE TABLE IF NOT EXISTS skus (
--     id                    BIGSERIAL       PRIMARY KEY,
--     listing_variant_id    BIGINT          NOT NULL REFERENCES listing_variants(id),
--     erp_item_code         VARCHAR(64)     NOT NULL UNIQUE,
--     size_label            VARCHAR(32),
--     stock_quantity        INTEGER         NOT NULL DEFAULT 0,
--     price                 NUMERIC(12, 2),
--     sale_price            NUMERIC(12, 2),
--     sale_ends_at          TIMESTAMPTZ,
--     created_at            TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
--     updated_at            TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
--     version               BIGINT          NOT NULL DEFAULT 0
-- );

-- -- 3. SEEDING LOGIC
-- DO $$
-- DECLARE
--     pb_id BIGINT;
--     lv_id BIGINT;
--     colors TEXT[] := ARRAY['Midnight Black', 'Slate Grey', 'Artic White', 'Forest Green', 'Ocean Blue', 'Ruby Red', 'Desert Sand', 'Lavender', 'Golden Amber', 'Mint Green'];
--     sizes TEXT[] := ARRAY['Small', 'Medium', 'Large', 'Extra Large'];
--     base_names TEXT[] := ARRAY[
--         'Essential Cotton T-Shirt', 'Premium Slim Fit Hoodie', 'Stretch Denim Jeans',
--         'Lightweight Windbreaker', 'Classic Canvas Sneakers', 'Performance Running Socks',
--         'Structured Baseball Cap', 'Waterproof Laptop Backpack', 'Minimalist Leather Wallet',
--         'Full Grain Leather Belt', 'Vintage Aviator Sunglasses', 'Minimalist Analog Watch',
--         'Soft Merino Wool Scarf', 'Insulated Winter Gloves', 'Active Performance Shorts',
--         'Pleated Midi Skirt', 'Sleeveless Summer Dress', 'Tailored Business Suit',
--         'Silk Patterned Tie', 'Rugged Waterproof Boots', 'Orthopedic Leather Sandals',
--         'Quick-Dry Swim Trunks', 'Seamless Comfort Underwear', 'Bamboo Breathable Pajamas',
--         'Organic Wool Sweater', 'Heavyweight Knit Cardigan', 'Modern Cut Blazer',
--         'All-Season Trench Coat', 'Windproof Compact Umbrella', 'Casual Canvas Tote Bag'
--     ];
--     base_templates TEXT[] := ARRAY[
--         'TPL-SHIRT-01', 'TPL-HOOD-02', 'TPL-JEAN-03', 'TPL-WIND-04', 'TPL-SNEAK-05',
--         'TPL-SOCK-06', 'TPL-CAP-07', 'TPL-PACK-08', 'TPL-WALL-09', 'TPL-BELT-10',
--         'TPL-SUN-11', 'TPL-WATCH-12', 'TPL-SCARF-13', 'TPL-GLOVE-14', 'TPL-SHORT-15',
--         'TPL-SKIRT-16', 'TPL-DRESS-17', 'TPL-SUIT-18', 'TPL-TIE-19', 'TPL-BOOT-20',
--         'TPL-SAND-21', 'TPL-SWIM-22', 'TPL-UNDER-23', 'TPL-PAJAM-24', 'TPL-SWEAT-25',
--         'TPL-CARD-26', 'TPL-BLAZ-27', 'TPL-COAT-28', 'TPL-UMB-29', 'TPL-BAG-30'
--     ];
--     i INT;
--     c INT;
--     s INT;
--     color_idx INT;
--     base_price NUMERIC;
--     v_slug TEXT;
-- BEGIN
--     FOR i IN 1..30 LOOP
--         -- Insert Product Base
--         INSERT INTO product_bases (erp_template_code, name)
--         VALUES (base_templates[i], base_names[i])
--         RETURNING id INTO pb_id;

--         -- Insert 3 Variants (Colors) for each Product
--         FOR c IN 1..3 LOOP
--             color_idx := ((i + c) % 10) + 1;
--             v_slug := lower(replace(base_names[i], ' ', '-')) || '-' || lower(replace(colors[color_idx], ' ', '-'));

--             INSERT INTO listing_variants (product_base_id, color_key, slug, web_description, top_selling)
--             VALUES (
--                 pb_id,
--                 colors[color_idx],
--                 v_slug,
--                 'Discover the ultimate comfort and style with our ' || base_names[i] || ' in ' || colors[color_idx] || '. Designed for durability and daily wear.',
--                 (i + c) % 7 = 0
--             )
--             RETURNING id INTO lv_id;

--             -- Add sample image
--             INSERT INTO listing_variant_images (listing_variant_id, image_url, sort_order)
--             VALUES (lv_id, 'https://images.unsplash.com/photo-' || (1500000000000 + i * 1000 + c * 100) || '?w=800', 1);

--             -- Insert 4 SKUs (Sizes) for each Variant
--             base_price := 25.00 + (i * 5.5);
--             FOR s IN 1..4 LOOP
--                 INSERT INTO skus (listing_variant_id, erp_item_code, size_label, stock_quantity, price)
--                 VALUES (
--                     lv_id,
--                     base_templates[i] || '-' || upper(substring(colors[color_idx] from 1 for 3)) || '-' || upper(substring(sizes[s] from 1 for 1)),
--                     sizes[s],
--                     50 + (i * 2),
--                     base_price + (s * 2.5)
--                 );
--             END LOOP;
--         END LOOP;
--     END LOOP;
-- END $$;
