package tj.radolfa.infrastructure.persistence.mappers;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import tj.radolfa.domain.model.Product;
import tj.radolfa.infrastructure.persistence.entity.ProductEntity;

/**
 * MapStruct mapper: {@link ProductEntity} (JPA) <-> {@link Product} (Domain).
 *
 * {@code componentModel = "spring"} makes the generated class a Spring bean
 * so it can be injected into adapters.
 */
@Mapper(componentModel = "spring")
public interface ProductMapper {

    /** Entity -> Domain */
    @Mapping(source = "topSelling", target = "topSelling")
    Product toProduct(ProductEntity entity);

    /**
     * Domain -> Entity.
     *
     * {@code id} is mapped when present (update path); it is null on the create path
     * and will be generated by the DB.
     * Timestamp fields are managed by JPA lifecycle hooks, so we ignore them here.
     */
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    ProductEntity toEntity(Product product);
}
