package tj.radolfa.infrastructure.persistence.mappers;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

import tj.radolfa.domain.model.Product;
import tj.radolfa.infrastructure.persistence.entity.ProductEntity;
import tj.radolfa.infrastructure.persistence.entity.ProductImageEntity;

import java.util.ArrayList;
import java.util.List;

/**
 * MapStruct mapper: {@link ProductEntity} (JPA) <-> {@link Product} (Domain).
 *
 * {@code componentModel = "spring"} makes the generated class a Spring bean
 * so it can be injected into adapters.
 */
@Mapper(componentModel = "spring")
public interface ProductMapper {

    /** Entity -> Domain */
    @Mapping(source = "topSelling", target = "topSelling")
    @Mapping(source = "images", target = "images", qualifiedByName = "imagesToUrls")
    Product toProduct(ProductEntity entity);

    /**
     * Domain -> Entity.
     *
     * {@code id} is mapped when present (update path); it is null on the create path
     * and will be generated by the DB.
     * Timestamp fields are managed by JPA lifecycle hooks, so we ignore them here.
     * Images are mapped via the adapter (requires back-pointer wiring).
     */
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "images", ignore = true)
    ProductEntity toEntity(Product product);

    // ---- Image helpers ------------------------------------------------

    @Named("imagesToUrls")
    default List<String> imagesToUrls(List<ProductImageEntity> entities) {
        if (entities == null) return List.of();
        return entities.stream()
                .map(ProductImageEntity::getImageUrl)
                .toList();
    }

    default List<ProductImageEntity> urlsToImages(List<String> urls) {
        if (urls == null) return new ArrayList<>();
        List<ProductImageEntity> entities = new ArrayList<>();
        for (int i = 0; i < urls.size(); i++) {
            ProductImageEntity img = new ProductImageEntity();
            img.setImageUrl(urls.get(i));
            img.setSortOrder(i);
            entities.add(img);
        }
        return entities;
    }
}
